### PR TITLE
bump sbt-precog

### PR DESCRIPTION
**Pull request by alissapajer**

### CODE REVIEW

**Comment by alissapajer** [comment]
🛑 until we figure out what's up with tectonic's sbt-precog bump

**Comment by alissapajer** [comment]
@jsantos17 got the build green. Thought about removing CI build for Java 8 entirely, but decided to keep it around for now. Once we have v3 fully working we can remove the Java 8 builds.

**Comment by alissapajer** [comment]
Since this repo isn't currently in the production path, I'm going to merge this now so I can verify that it publishes and easily use the dependency over in scion. I'll address any PR feedback in a subsequent PR.

**Review by jsantos17 — COMMENTED** [review]
Looks good to me. For some reason I can't approve this.

**Comment by alissapajer** [comment]
Maybe github changed it so you can't approve a merged PR.

**Pull request merged**
